use lib::{wavefront_alignment::wavefront_align, alignment_lib::Penalties, reference::{self, affine_gap_align}};


fn main() {
    use std::time::Instant;
    
let a = "ATGCACGGTGGTAGGTGCGGTCCCGCTGAGGAGACTCACCGTATGTGCACTATACCCCACAGGTTAGCATGTTTGGGCTGTTGGTAACCCTGACCTCTAGTTCGGACAGATCTGATGCAAGTGGCACGTGATCGCATGCCTATTGTGAATCTGTCAAGGACTTTGCTCTATTAGGTGATTTAGGATGAGCCACATACTGCTCAAAGTGTTGTACCCCACTGGAATTAAGTCGACGCAGAACGTCTCTAGCAAAACTAGTTCCCGTATTGTTAGTGCACGGGTTGACCATCTCGATCCTCTGATAACGAGCTAATTAAACACACTCACGTGGGTCTTTCAGTATTTGAAGCAAGGATGCGGTACTGAGCGGTCTTCGCGTATAACGCCCTTAGACGGGAACTAGGTACAGCCGCGATTCCGCCCCTTACACGTCCGAGACCCTTTCTTAAATGGAACAATACGATTGACTGGACGAGCTGGTGCGGCTTGTTACTTCGTGCCCGTAGCCGAAGGCACTAACTTCCTCGCCCTTTGGTCTCTAGCGTGTTGTAGTGTGAGACTACGGTCATTATCCGCAGATCCGCACAAACGTCTCATTAGGCGAGACTGCGAGAGGGGTGACGCATGTTTGGACGTGTGCCCCTCAGATCGTGACTAATATGGATCTCCGGGTAGAAACAGTTCACCACACCGACGCATGGGAGGGTTTATGTTTACACGCGTAGAGTCCGATTGGGGCCGCAGCAGGATCGCCGAGCATGGAGGTCACTGTCGCGGACTTGGCACGGGGGCCGATGCATAGGCCAAAACTTACCCGTTCGGGTAGTTTTGAGAGTCGTCATCCCTGAGGCAATACGTACTGGCTACCTAGAAACCTACCTTGTTGCCGGTCCCTCGAGCCAGCCATAACGTAATTTCAGTATCCGGATAGACACGAAGACAAGCAGAGTGCTGGCCCCACTCGTTATATAGACACGGGACCCCTAGCCTGTGTCCGGCG";
let b = "AGACGCGGGCTCGAGGACCCACAAATAGCTAACTCCAAATTGCAGAAATACCACTAGCATGTGTTCTCAAAGTGAGTAGCGTCCTGCAATTAACGGTTCACTATAGCGTCATGCTCCTTACGGGAACGTGCTTTCCAATGTAGGAAAGGAAAGTAAAATAATGCAAACTAGGTACCCGGCATACGGAAACGGGGTTATCAATGAATTGTGTATGAGTAACGGTAAAGCCAACCATCGAGCGCGTCCCTCGGCGGGCATCACAGGGTCTGGGAACTCAGGCGGCGAATTATTCTGTGCGTTGCCGTCGACACCCTGAGGCCACAGTGTACCTTTCTAGCGCGCCTCCGTCGCCTGACGTCAGCTAGGTGGATGCGGTCTTCTAACGTAACATCCGGTTTCCCGCCAAATGATATTAGGGGGGACTCACACAACCTTGTCTCAGGACACAAACTAGTGGTCCCGTTGAGGGGCATGCTGACTATAACAAAAGCACTTATCTGATTACGGAGAAGCGATCATTACTCTATGTCTGTTGATATTTCAAACGCGGCGCCAGACCAACTAGCCCAGCACCATATTGCTTCGTCATTATCGGCCTGTCGCCCGATAATTGCTATCGCACACGACAAGTATTGATACCCAATCGCGGGACCGATTTGATCTCCGCGACGCGAGGTTATCCGTAAGCGATAACGAAATGTAGTTATCCCGCCTGCTGTGCCAGCCTACGCGAACGCTAAGTCGGGTGTGTGGATAAGTGTCAAAGAATACCGTCCCTCCGCAATTTCGCCGGCTGCACTTAGACGAGTCTCCTGCCAGCAGCCCGTGGGGAACGTCGTTCTCATTGAGCGGAATTGTTACAGAACAATGAATAGCTTATGCATAACGTGATTCAGCGATATCCACCACGTCCAACTAGCTAACCAGAAAGTCTGGTCACTCCTAGTGGGATGACACCGTTATTCTACTCTTAAATCACGCGGAGAGCAAAAGACAACGCAGAGCATACCCTGGGACATACCTTCTATTGCACGCAACATAGCGATCAC";

    let now = Instant::now();
    wavefront_align(a, b, &Penalties {
        mismatch_pen: 6,
        open_pen: 2,
        extd_pen: 4,
        }
    );

    let t = now.elapsed();
    println!("{:.2?}", t);

    let now = Instant::now();
    affine_gap_align(a, b, &Penalties {
        mismatch_pen: 6,
        open_pen: 2,
        extd_pen: 4,
        }
    );

    let t = now.elapsed();
    println!("{:.2?}", t);
}
